pipeline {
    agent any
        stages{
            stage('step 1'){
                steps{
                    sh 'echo hello'
                }
            }
            stage('step 2'){
                steps {
                sh 'docker build -t One .'
            }
        }
    }
}